### ISSUE TITLE
您好，请问对于fast-livo中使用的NTU公开数据集适配吗？

### ISSUE THREAD

**Issue by hr2894235132** [ToutDonner/FAST-LIVO-DiffTime#4]
您好，非常优秀的工作呀，想问一下对于NTU数据集里面的相机，可以使用嘛？您有没有做过尝试。

**Comment by RuizhiChang** [comment]
@hr2894235132 我没记错的话是没跑成功的。。。不过我现在还在做新的版本，等毕业了连带着硬件驱动一起开源掉吧

**Comment by hr2894235132** [comment]
> @hr2894235132 我没记错的话是没跑成功的。。。不过我现在还在做新的版本，等毕业了连带着硬件驱动一起开源掉吧

好的感谢，期待后续工作。

**Comment by RuizhiChang** [comment]
> > @hr2894235132 我没记错的话是没跑成功的。。。不过我现在还在做新的版本，等毕业了连带着硬件驱动一起开源掉吧
> 
> 好的感谢，期待后续工作。

修改了一版，可以直接跑NTU数据集。之前只更新bias的方案不对，重新推了下公式
