### ISSUE TITLE
您好，您指的软同步是在lasermapping中进行同步吗？

### ISSUE THREAD

**Issue by STRlll1** [ToutDonner/FAST-LIVO-DiffTime#5]
您好，非常感谢您开源这个优秀的工作，我想问一下您说的可以使用软同步的雷达和相机指的是直接录制二者的bag，然后在config中修改image_time_offset进行软同步，还是要事先进行软同步，再录制bag。

**Comment by RuizhiChang** [comment]
> 您好，非常感谢您开源这个优秀的工作，我想问一下您说的可以使用软同步的雷达和相机指的是直接录制二者的bag，然后在config中修改image_time_offset进行软同步，还是要事先进行软同步，再录制bag。

要先进行软同步，两个传感器使用系统时间（ptp），image time offset是为了获取图像的真实采集时刻的补偿值。
