### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by xueli-guo** [ToutDonner/FAST-LIVO-DiffTime#6]
您好，非常感谢修改并开源，但我编译时候遇到一个问题，如下
  if (pl_orig.points[plsize - 1].time > 0) {
    given_offset_time = true;
  } else {

我检查到pcl::PointCloud<velodyne_ros::Point> pl_orig;这个定义中并没有time这个字段，定义如下
namespace velodyne_ros {
  struct EIGEN_ALIGN16 Point {
      PCL_ADD_POINT4D;
      float intensity;
      uint16_t ring;
      EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  };
}  // namespace velodyne_ros
请问您这里这么处理的呢？

**Comment by RuizhiChang** [comment]
> 您好，非常感谢修改并开源，但我编译时候遇到一个问题，如下 if (pl_orig.points[plsize - 1].time > 0) { given_offset_time = true; } else {
> 
> 我检查到pcl::PointCloud<velodyne_ros::Point> pl_orig;这个定义中并没有time这个字段，定义如下 namespace velodyne_ros { struct EIGEN_ALIGN16 Point { PCL_ADD_POINT4D; float intensity; uint16_t ring; EIGEN_MAKE_ALIGNED_OPERATOR_NEW }; } // namespace velodyne_ros 请问您这里这么处理的呢？

您好 麻烦截图我看一下或者复制一下终端中的报错
